//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace EPOSmobile.Domain.Entities
{
    public partial class EPOSmobileContext : ObjectContext
    {
        public const string ConnectionString = "name=EPOSmobileContext";
        public const string ContainerName = "EPOSmobileContext";
    
        #region Constructors
    
        public EPOSmobileContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EPOSmobileContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EPOSmobileContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<Menu> Menus
        {
            get { return _menus  ?? (_menus = CreateObjectSet<Menu>("Menus")); }
        }
        private ObjectSet<Menu> _menus;
    
        public ObjectSet<Employee> Employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<Employee>("Employees")); }
        }
        private ObjectSet<Employee> _employees;
    
        public ObjectSet<Address> Addresses
        {
            get { return _addresses  ?? (_addresses = CreateObjectSet<Address>("Addresses")); }
        }
        private ObjectSet<Address> _addresses;
    
        public ObjectSet<Sales> Sales
        {
            get { return _sales  ?? (_sales = CreateObjectSet<Sales>("Sales")); }
        }
        private ObjectSet<Sales> _sales;
    
        public ObjectSet<Shift> Shifts
        {
            get { return _shifts  ?? (_shifts = CreateObjectSet<Shift>("Shifts")); }
        }
        private ObjectSet<Shift> _shifts;
    
        public ObjectSet<ProductGroup> ProductGroups
        {
            get { return _productGroups  ?? (_productGroups = CreateObjectSet<ProductGroup>("ProductGroups")); }
        }
        private ObjectSet<ProductGroup> _productGroups;
    
        public ObjectSet<ShiftSchedule> ShiftSchedules
        {
            get { return _shiftSchedules  ?? (_shiftSchedules = CreateObjectSet<ShiftSchedule>("ShiftSchedules")); }
        }
        private ObjectSet<ShiftSchedule> _shiftSchedules;
    
        public ObjectSet<Order> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Order>("Orders")); }
        }
        private ObjectSet<Order> _orders;
    
        public ObjectSet<OrderItem> OrderItems
        {
            get { return _orderItems  ?? (_orderItems = CreateObjectSet<OrderItem>("OrderItems")); }
        }
        private ObjectSet<OrderItem> _orderItems;
    
        public ObjectSet<Room> Rooms
        {
            get { return _rooms  ?? (_rooms = CreateObjectSet<Room>("Rooms")); }
        }
        private ObjectSet<Room> _rooms;
    
        public ObjectSet<Table> Tables
        {
            get { return _tables  ?? (_tables = CreateObjectSet<Table>("Tables")); }
        }
        private ObjectSet<Table> _tables;

        #endregion
    }
}
