//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace EPOSmobile.Domain.Entities
{
    public partial class Menu
    {
        #region Primitive Properties
    
        public virtual int MenuID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ProductGroup> ProductGroups
        {
            get
            {
                if (_productGroups == null)
                {
                    var newCollection = new FixupCollection<ProductGroup>();
                    newCollection.CollectionChanged += FixupProductGroups;
                    _productGroups = newCollection;
                }
                return _productGroups;
            }
            set
            {
                if (!ReferenceEquals(_productGroups, value))
                {
                    var previousValue = _productGroups as FixupCollection<ProductGroup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductGroups;
                    }
                    _productGroups = value;
                    var newValue = value as FixupCollection<ProductGroup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductGroups;
                    }
                }
            }
        }
        private ICollection<ProductGroup> _productGroups;

        #endregion
        #region Association Fixup
    
        private void FixupProductGroups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductGroup item in e.NewItems)
                {
                    item.Menu = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductGroup item in e.OldItems)
                {
                    if (ReferenceEquals(item.Menu, this))
                    {
                        item.Menu = null;
                    }
                }
            }
        }

        #endregion
    }
}
