//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace EPOSmobile.Domain.Entities
{
    public partial class ProductGroup
    {
        #region Primitive Properties
    
        public virtual int ProductGroupID
        {
            get;
            set;
        }
    
        public virtual string GroupName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Menu Menu
        {
            get { return _menu; }
            set
            {
                if (!ReferenceEquals(_menu, value))
                {
                    var previousValue = _menu;
                    _menu = value;
                    FixupMenu(previousValue);
                }
            }
        }
        private Menu _menu;
    
        public virtual ICollection<Product> Products
        {
            get
            {
                if (_products == null)
                {
                    var newCollection = new FixupCollection<Product>();
                    newCollection.CollectionChanged += FixupProducts;
                    _products = newCollection;
                }
                return _products;
            }
            set
            {
                if (!ReferenceEquals(_products, value))
                {
                    var previousValue = _products as FixupCollection<Product>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProducts;
                    }
                    _products = value;
                    var newValue = value as FixupCollection<Product>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProducts;
                    }
                }
            }
        }
        private ICollection<Product> _products;

        #endregion
        #region Association Fixup
    
        private void FixupMenu(Menu previousValue)
        {
            if (previousValue != null && previousValue.ProductGroups.Contains(this))
            {
                previousValue.ProductGroups.Remove(this);
            }
    
            if (Menu != null)
            {
                if (!Menu.ProductGroups.Contains(this))
                {
                    Menu.ProductGroups.Add(this);
                }
            }
        }
    
        private void FixupProducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Product item in e.NewItems)
                {
                    item.ProductGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Product item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductGroup, this))
                    {
                        item.ProductGroup = null;
                    }
                }
            }
        }

        #endregion
    }
}
