//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace EPOSmobile.Domain.Entities
{
    public partial class Room
    {
        #region Primitive Properties
    
        public virtual int RoomID
        {
            get;
            set;
        }
    
        public virtual string RoomNumber
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Table> Tables
        {
            get
            {
                if (_tables == null)
                {
                    var newCollection = new FixupCollection<Table>();
                    newCollection.CollectionChanged += FixupTables;
                    _tables = newCollection;
                }
                return _tables;
            }
            set
            {
                if (!ReferenceEquals(_tables, value))
                {
                    var previousValue = _tables as FixupCollection<Table>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTables;
                    }
                    _tables = value;
                    var newValue = value as FixupCollection<Table>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTables;
                    }
                }
            }
        }
        private ICollection<Table> _tables;

        #endregion
        #region Association Fixup
    
        private void FixupTables(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Table item in e.NewItems)
                {
                    item.Room = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Table item in e.OldItems)
                {
                    if (ReferenceEquals(item.Room, this))
                    {
                        item.Room = null;
                    }
                }
            }
        }

        #endregion
    }
}
