//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace EPOSmobile.Domain.Entities
{
    public partial class ShiftSchedule
    {
        #region Primitive Properties
    
        public virtual int ShiftScheduleID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Shift> Shifts
        {
            get
            {
                if (_shifts == null)
                {
                    var newCollection = new FixupCollection<Shift>();
                    newCollection.CollectionChanged += FixupShifts;
                    _shifts = newCollection;
                }
                return _shifts;
            }
            set
            {
                if (!ReferenceEquals(_shifts, value))
                {
                    var previousValue = _shifts as FixupCollection<Shift>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupShifts;
                    }
                    _shifts = value;
                    var newValue = value as FixupCollection<Shift>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupShifts;
                    }
                }
            }
        }
        private ICollection<Shift> _shifts;

        #endregion
        #region Association Fixup
    
        private void FixupShifts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Shift item in e.NewItems)
                {
                    item.ShiftSchedule = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Shift item in e.OldItems)
                {
                    if (ReferenceEquals(item.ShiftSchedule, this))
                    {
                        item.ShiftSchedule = null;
                    }
                }
            }
        }

        #endregion
    }
}
